name : Java CI with Maven - Test and Package

on:
    pull_request:
        branches: main
jobs:
    build :
      name: Build with maven
      runs-on: ubuntu-latest
      steps : 
        - name : Checkout repository
          uses: actions/checkout@v4
        - name : Setup JDK
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'corretto'
        - name: Build package with maven
          run: mvn -B package
          
          
            
            

            



