name : Java CI with Maven - Test and Package
#fix sonar token problem
on:
    pull_request:
        branches: main
jobs:
    build :
      name: Build with maven
      runs-on: ubuntu-latest
      steps : 
        - name : Checkout repository
          uses: actions/checkout@v4
        - name : Setup JDK
          uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'corretto'
        - name: Build package with maven
          env:
            SONAR_TOKEN : ${{secrets.SONAR_TOKEN}}  
          run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-') -Dsonar.organization=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')

          
          
            
            

            



